[env:t_display]
platform = espressif32
board = ttgo-t1
framework = arduino
board_build.partitions = huge_app.csv

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DLGFX_USE_V1

lib_deps =
    lovyan03/LovyanGFX @ ^1.2.21
    bblanchon/ArduinoJson @ ^7.4.3

monitor_speed = 115200
upload_speed = 921600
